var vocabularioComidaList = [
  { q: "agua", a: "みず" }/*,
  { q: "arroz", a: "ごはん" },
  { q: "pan", a: "パン" },
  { q: "sopa", a: "スープ" },
  { q: "carne", a: "にく" },
  { q: "pollo", a: "とりにく" },
  { q: "pescado", a: "さかな" },
  { q: "mariscos", a: "かいせん" },
  { q: "verduras", a: "やさい" },
  { q: "fruta", a: "くだもの" },
  { q: "manzana", a: "りんご" },
  { q: "plátano", a: "バナナ" },
  { q: "naranja", a: "みかん" },
  { q: "fresa", a: "いちご" },
  { q: "queso", a: "チーズ" },
  { q: "huevo", a: "たまご" },
  { q: "leche", a: "ぎゅうにゅう" },
  { q: "té", a: "おちゃ" },
  { q: "café", a: "コーヒー" },
  { q: "jugo", a: "ジュース" },
  { q: "cerveza", a: "ビール" },
  { q: "vino", a: "ワイン" },
  { q: "sal", a: "しお" },
  { q: "azúcar", a: "さとう" },
  { q: "aceite", a: "あぶら" },
  { q: "pimienta", a: "こしょう" },
  { q: "miel", a: "はちみつ" },
  { q: "postre", a: "デザート" },
  { q: "helado", a: "アイスクリーム" },
  { q: "pastel", a: "ケーキ" },
  { q: "ensalada", a: "サラダ" },
  { q: "fideos", a: "めん" },
  { q: "sushi", a: "すし" },
  { q: "ramen", a: "ラーメン" },
  { q: "tempura", a: "てんぷら" },
  { q: "tofu", a: "とうふ" },
  { q: "soja", a: "しょうゆ" },
  { q: "pollo frito", a: "からあげ" },
  { q: "arroz frito", a: "チャーハン" },
  { q: "papas fritas", a: "ポテト" },
  { q: "pizza", a: "ピザ" },
  { q: "hamburguesa", a: "ハンバーガー" },
  { q: "sándwich", a: "サンドイッチ" },
  { q: "japonés", a: "にほんしょく" },
  { q: "occidental", a: "ようしょく" },
  { q: "picante", a: "からい" },
  { q: "dulce", a: "あまい" },
  { q: "salado", a: "しおからい" },
  { q: "amargo", a: "にがい" },
  { q: "ácido", a: "すっぱい" }*/
];
