var vocabularioComidaList = [
  { q: "agua", a: "みず", r: "mizu" },
  { q: "arroz", a: "ごはん", r: "gohan" },
  { q: "pan", a: "パン", r: "pan" },
  { q: "sopa", a: "スープ", r: "suupu" },
  { q: "carne", a: "にく", r: "niku" },
  { q: "pollo", a: "とりにく", r: "toriniku" },
  { q: "pescado", a: "さかな", r: "sakana" },
  { q: "mariscos", a: "かいせん", r: "kaisen" },
  { q: "verduras", a: "やさい", r: "yasai" },
  { q: "fruta", a: "くだもの", r: "kudamono" },
  { q: "manzana", a: "りんご", r: "ringo" },
  { q: "plátano", a: "バナナ", r: "banana" },
  { q: "naranja", a: "みかん", r: "mikan" },
  { q: "fresa", a: "いちご", r: "ichigo" },
  { q: "queso", a: "チーズ", r: "chiizu" },
  { q: "huevo", a: "たまご", r: "tamago" },
  { q: "leche", a: "ぎゅうにゅう", r: "gyuunyuu" },
  { q: "té", a: "おちゃ", r: "ocha" },
  { q: "café", a: "コーヒー", r: "koohii" },
  { q: "jugo", a: "ジュース", r: "juusu" },
  { q: "cerveza", a: "ビール", r: "biiru" },
  { q: "vino", a: "ワイン", r: "wain" },
  { q: "sal", a: "しお", r: "shio" },
  { q: "azúcar", a: "さとう", r: "satou" },
  { q: "aceite", a: "あぶら", r: "abura" },
  { q: "pimienta", a: "こしょう", r: "koshou" },
  { q: "miel", a: "はちみつ", r: "hachimitsu" },
  { q: "postre", a: "デザート", r: "dezaato" },
  { q: "helado", a: "アイスクリーム", r: "aisukuriimu" },
  { q: "pastel", a: "ケーキ", r: "keeki" },
  { q: "ensalada", a: "サラダ", r: "sarada" },
  { q: "fideos", a: "めん", r: "men" },
  { q: "sushi", a: "すし", r: "sushi" },
  { q: "ramen", a: "ラーメン", r: "raamen" },
  { q: "tempura", a: "てんぷら", r: "tenpura" },
  { q: "tofu", a: "とうふ", r: "toufu" },
  { q: "soja", a: "しょうゆ", r: "shouyu" },
  { q: "pollo frito", a: "からあげ", r: "karaage" },
  { q: "arroz frito", a: "チャーハン", r: "chaahan" },
  { q: "papas fritas", a: "ポテト", r: "poteto" },
  { q: "pizza", a: "ピザ", r: "piza" },
  { q: "hamburguesa", a: "ハンバーガー", r: "hanbaagaa" },
  { q: "sándwich", a: "サンドイッチ", r: "sandoicchi" },
  { q: "japonés", a: "にほんしょく", r: "nihonshoku" },
  { q: "occidental", a: "ようしょく", r: "youshoku" },
  { q: "picante", a: "からい", r: "karai" },
  { q: "dulce", a: "あまい", r: "amai" },
  { q: "salado", a: "しおからい", r: "shiokarai" },
  { q: "amargo", a: "にがい", r: "nigai" },
  { q: "ácido", a: "すっぱい", r: "suppai" }
];
