var vocabularioSaludoList = [
  { q: "hola", a: "こんにちは", r: "konnichiwa" },
  { q: "buenos días", a: "おはようございます", r: "ohayou gozaimasu" },
  { q: "buenas noches", a: "こんばんは", r: "konbanwa" },
  { q: "adiós", a: "さようなら", r: "sayounara" },
  { q: "gracias", a: "ありがとう", r: "arigatou" },
  { q: "muchas gracias", a: "ありがとうございます", r: "arigatou gozaimasu" },
  { q: "perdón / disculpe", a: "すみません", r: "sumimasen" },
  { q: "sí", a: "はい", r: "hai" },
  { q: "no", a: "いいえ", r: "iie" },
  { q: "¿cómo estás?", a: "おげんきですか？", r: "ogenki desu ka?" },
  { q: "estoy bien", a: "げんきです", r: "genki desu" },
  { q: "encantado de conocerte", a: "よろしくおねがいします", r: "yoroshiku onegaishimasu" },
  { q: "por favor", a: "おねがいします", r: "onegaishimasu" },
  { q: "con permiso", a: "しつれいします", r: "shitsurei shimasu" },
  { q: "lo siento", a: "ごめんなさい", r: "gomen nasai" },
  { q: "nos vemos", a: "またね", r: "mata ne" },
  { q: "hasta luego", a: "じゃあね", r: "jaa ne" },
  { q: "felicidades", a: "おめでとうございます", r: "omedetou gozaimasu" },
  { q: "bienvenido", a: "ようこそ", r: "youkoso" },
  { q: "buen trabajo", a: "おつかれさまです", r: "otsukaresama desu" },
  { q: "expresión antes de comer", a: "いただきます", r: "itadakimasu" },
  { q: "expresión después de comer", a: "ごちそうさまでした", r: "gochisousama deshita" },
  { q: "te amo", a: "あいしています", r: "aishiteimasu" },
  { q: "ánimo / esfuérzate", a: "がんばってください", r: "ganbatte kudasai" },
  { q: "no entiendo", a: "わかりません", r: "wakarimasen" },
  { q: "entiendo", a: "わかりました", r: "wakarimashita" },
  { q: "por supuesto", a: "もちろん", r: "mochiron" },
  { q: "realmente", a: "ほんとうに", r: "hontou ni" },
  { q: "ayuda", a: "たすけて", r: "tasukete" },
  { q: "peligro", a: "あぶない", r: "abunai" },
  { q: "bonito / limpio", a: "きれい", r: "kirei" },
  { q: "rápido", a: "はやい", r: "hayai" },
  { q: "despacio", a: "ゆっくり", r: "yukkuri" },
  { q: "sí, claro", a: "ええ", r: "ee" },
  { q: "miedo", a: "こわい", r: "kowai" },
  { q: "bien", a: "いい", r: "ii" },
  { q: "mal", a: "わるい", r: "warui" },
  { q: "nunca", a: "ぜんぜん", r: "zenzen" },
  { q: "a veces", a: "ときどき", r: "tokidoki" },
  { q: "ahora", a: "いま", r: "ima" },
  { q: "antes", a: "まえ", r: "mae" },
  { q: "después", a: "あと", r: "ato" },
  { q: "ayer", a: "きのう", r: "kinou" },
  { q: "mañana (día siguiente)", a: "あした", r: "ashita" },
  { q: "ayer por la noche", a: "ゆうべ", r: "yuube" },
  { q: "buenas noches (al dormir)", a: "おやすみなさい", r: "oyasuminasai" }
];
